name: Validate Docs
on:
  push:
    paths: [ "docs/**", "scripts/**", ".github/workflows/validate-docs.yml" ]
  pull_request:
    paths: [ "docs/**", "scripts/**", ".github/workflows/validate-docs.yml" ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm ci || pnpm i || yarn
      - run: npm run validate:docs || pnpm run validate:docs || yarn validate:docs